"""Initial schema

Revision ID: 16d9006fd983
Revises: 
Create Date: 2026-02-28 16:13:10.956762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d9006fd983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_auth_token_encrypted', sa.Text(), nullable=True),
    sa.Column('twilio_service_sid', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tracking_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('twilio_phone_number', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('partner_phone', sa.String(length=20), nullable=True),
    sa.Column('cost_per_lead', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tracking_line_id', sa.Integer(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_recording_sid', sa.String(length=255), nullable=True),
    sa.Column('caller_number', sa.String(length=20), nullable=True),
    sa.Column('call_duration', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('transcript_sid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=True),
    sa.Column('full_transcript', sa.Text(), nullable=True),
    sa.Column('analysed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tracking_line_id'], ['tracking_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tracking_line_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('booked_calls', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tracking_line_id'], ['tracking_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('calls')
    op.drop_table('tracking_lines')
    op.drop_table('accounts')
    # ### end Alembic commands ###
